### ISSUE TITLE
change name of landscape creator function

### ISSUE THREAD

**Issue by corybrunson** [corybrunson/plt#5]
The function `landscape()` causes conflicts with `TDA::landscape()`, which should be avoided because it will often be useful to use the packages together.

Based on conventions in other packages, and reflecting the underlying use of `$new()`, i suggest that this function be renamed `pl_new()`.

**Comment by corybrunson** [comment]
@jamesgolabek22 @a1danbryant do you foresee any issues with this change?

**Comment by jamesgolabek22** [comment]
@corybrunson That looks great to me.

**Comment by corybrunson** [comment]
So renamed in [the `new` branch](https://github.com/corybrunson/plt/tree/new).

**Comment by corybrunson** [comment]
Resolved in 8c0d2e14263e348b3e5f23fd6f282eacb76fe7e5.
